[package]
name = "afpa-document"
version = "0.1.0"
compiler = "0.11.1"
entrypoint = "lib.typ"
repository = "https://github.com/ludovic-esperce/afpa-typst-template"
authors = ["Ludovic Esperce"]
license = "MIT-0"
description = "Template utilisable pour les documents internes à l'Afpa ainsi que les ressources pédagogiques."
keywords = ["Formation", "Afpa", "Ressources pédagogiques"]
categories = ["paper"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
